Feature/comp sign up
arthurpaesrizon/marvelpedia-orionis-front pull request #15
Opened 2023-10-31 22:44 UTC by rodrigodip

2023-11-01 22:33 UTC, arthurpaesrizon requested changes
Dá uma boa revisada no código

2023-11-01 22:33 UTC, arthurpaesrizon commented on src/app/pages/sign-up/interfaces/sign-up.interface.ts
> +export interface SignUp {
Algo que esqueci de mencionar: sempre usar I maiúsculo para nomear interfaces:
ISignUp

2023-11-01 22:33 UTC, arthurpaesrizon commented on src/app/pages/sign-up/interfaces/sign-up.interface.ts
> +export interface Checker {
Algo que esqueci de mencionar: sempre usar I maiúsculo para nomear interfaces:

2023-11-01 22:33 UTC, arthurpaesrizon commented on src/app/pages/sign-up/interfaces/sign-up.interface.ts
> +export interface Formatter {
Algo que esqueci de mencionar: sempre usar I maiúsculo para nomear interfaces:

2023-11-01 22:33 UTC, arthurpaesrizon commented on src/app/pages/sign-up/sign-up.component.ts
> +  optionList: string[] = [
É bom colocares public ou private antes de cada variável

2023-11-01 22:33 UTC, arthurpaesrizon commented on src/app/pages/sign-up/sign-up.component.ts
> +  borderColor: SignUp = <SignUp>new Object();
Não entendi esse nome de variável com interface signUp? Muito confuso

2023-11-01 22:33 UTC, arthurpaesrizon commented on src/app/pages/sign-up/sign-up.component.html
> +      [inputBorderColor]="borderColor.email"
email dentro de bordercolor?

2023-11-01 22:33 UTC, arthurpaesrizon commented on src/app/pages/sign-up/sign-up.component.html
> +        [inputBorderColor]="borderColor.birthDate"
birthDate dentro de borderColor? Isso tá muito estranho

2023-11-03 15:00 UTC, rodrigodip commented on src/app/pages/sign-up/sign-up.component.ts
> +  borderColor: SignUp = <SignUp>new Object();
Este nome realmente não ficou intuitivo. Este objeto recebe o border-color azul ou vermelho que será aplicado no input caso o valor do input passe, ou não, na verificação de requisitos do input. Criei usando a interface ISignup para ele ter as mesmas propriedades do objeto signUpformData.
Vou usar um nome melhor.

2023-11-06 17:36 UTC, arthurpaesrizon approved these changes

2023-11-06 17:36 UTC, arthurpaesrizon commented on src/app/pages/sign-up/sign-up.component.ts
> +   * receiveStatus
Nome poderia ser mais descritivo

2023-11-06 17:36 UTC, arthurpaesrizon commented on src/app/pages/sign-up/sign-up.component.ts
> +   * Toggles the Register button between anabled/disabled states.
enabled*

2023-11-06 17:36 UTC, arthurpaesrizon commented on src/app/pages/sign-up/InputData.ts
> +export class InputElement {
Esse classe e necessária? Não consegues pensar em outro jeito de implementar?

2023-11-06 22:05 UTC, rodrigodip commented on src/app/pages/sign-up/sign-up.component.ts
> +   * receiveStatus
Entendido.

2023-11-06 22:06 UTC, rodrigodip commented on src/app/pages/sign-up/sign-up.component.ts
> +   * Toggles the Register button between anabled/disabled states.
Verdade. Inventei um inglês aí.

2023-11-06 22:07 UTC, rodrigodip commented on src/app/pages/sign-up/InputData.ts
> +export class InputElement {
Queria discutir isso com você depois.

2023-11-07 11:47 UTC, merged