Bugfix/inputSelect
arthurpaesrizon/marvelpedia-orionis-front pull request #16
Opened 2023-11-01 01:59 UTC by rhorauti

2023-11-01 22:34 UTC, arthurpaesrizon requested changes
Colocaste o Merge pra master. Troca a branch e refaz o PR para poder ser revisado

2023-11-02 12:17 UTC, rhorauti commented
> Colocaste o Merge pra master. Troca a branch e refaz o PR para poder ser revisado

Desculpe. Alterei agora.

2023-11-06 17:18 UTC, arthurpaesrizon requested changes

2023-11-06 17:18 UTC, arthurpaesrizon commented on src/app/core/api/app/new.user.api.ts
> +  @Injectable()
Esse Injectable não deveria estar aqui. Deveria estar antes da declaração da classe

2023-11-06 17:18 UTC, arthurpaesrizon commented on src/app/core/api/app/new.user.api.ts
Injectable deveria estar aqui

2023-11-06 17:18 UTC, arthurpaesrizon commented on src/app/core/api/app/auth.api.ts
> +  @Injectable()
Mesma coisa aqui

2023-11-06 17:18 UTC, arthurpaesrizon commented on src/app/components/select/select.component.ts
>    /**
Falta o nome da função no tsDoc

2023-11-07 14:39 UTC, rhorauti commented on src/app/core/api/app/new.user.api.ts
> +  @Injectable()
Ok . Alterado

2023-11-07 14:39 UTC, rhorauti commented on src/app/core/api/app/auth.api.ts
> +  @Injectable()
Ok. Alterado

2023-11-07 14:39 UTC, rhorauti commented on src/app/components/select/select.component.ts
>    /**
Ok. Incluido

2023-11-08 13:17 UTC, arthurpaesrizon commented
Resolver conflitos

2023-11-08 20:58 UTC, arthurpaesrizon approved these changes

2023-11-08 20:59 UTC, merged