Componente Checkbox
arthurpaesrizon/marvelpedia-orionis-front pull request #2
Opened 2023-10-19 23:52 UTC by brennerpaiva

O componente checkbox foi criado, porém ainda não é funcional.

2023-10-20 11:35 UTC, arthurpaesrizon requested changes

2023-10-20 11:35 UTC, arthurpaesrizon commented on src/app/components/checkbox/checkbox.component.html
> +  <label for="checkbox" id="checkbox">Lembrar de mim</label>
Essa label deveria ser uma prop de forma a deixar o componente genérico e dinâmico

2023-10-20 11:35 UTC, arthurpaesrizon commented on src/app/components/checkbox/checkbox.component.ts
> +export class CheckboxComponent {}
Acho que seria necessário implementar uma lógica para armazenar o atual valor do checkbox (true/false) e comunicar esse valor para o componente pai.

2023-10-20 13:03 UTC, brennerpaiva commented on src/app/components/checkbox/checkbox.component.html
> +  <label for="checkbox" id="checkbox">Lembrar de mim</label>
Boa, vou implementar.

2023-10-20 13:04 UTC, brennerpaiva commented on src/app/components/checkbox/checkbox.component.ts
> +export class CheckboxComponent {}
Boa, vou implementar.

2023-10-23 13:40 UTC, arthurpaesrizon requested changes

2023-10-23 13:40 UTC, arthurpaesrizon commented on src/app/components/checkbox/checkbox.component.ts
> +  onCheckboxChange(event: Event) {
Não cobramos durante os exercícios, mas vamos usar tsDoc no projeto para a documentação de funções https://tsdoc.org/

2023-10-23 13:40 UTC, arthurpaesrizon commented on src/app/components/checkbox/checkbox.component.ts
> +  onCheckboxChange(event: Event) {
Podes tipar o retorno da função

2023-10-23 17:32 UTC, brennerpaiva commented on src/app/components/checkbox/checkbox.component.ts
> +  onCheckboxChange(event: Event) {
Feito!

2023-10-23 17:33 UTC, brennerpaiva commented on src/app/components/checkbox/checkbox.component.ts
> +  onCheckboxChange(event: Event) {
Confesso que nunca tinha ouvido falar do tsDoc, vou pesquisar mais sobre.

2023-10-24 21:48 UTC, arthurpaesrizon approved these changes

2023-10-24 21:48 UTC, merged