Feature/pesquisa
arthurpaesrizon/marvelpedia-orionis-front pull request #29
Opened 2023-11-13 03:17 UTC by rhorauti

2023-11-13 19:42 UTC, arthurpaesrizon requested changes

2023-11-13 19:42 UTC, arthurpaesrizon commented on src/app/core/api/app/auth.api.ts
> +    private httpRedirect: HttpRequestService,
Por que importaste o mesmo service duas vezes com nomes diferentes?

2023-11-13 19:42 UTC, arthurpaesrizon commented on src/app/core/api/app/auth.api.ts
> +   * redirectInfo
Faltou mudar o nome da função no tsDoc

2023-11-13 19:42 UTC, arthurpaesrizon commented on src/app/core/api/app/auth.api.ts
>  export class authApi {
Declaração de classe com Letra maiúscula

2023-11-13 19:42 UTC, arthurpaesrizon commented on src/app/pages/auth/redirect/redirect.component.ts
> +    private httpRedirect: authApi,
Trocar o nome da classe para AuthApi e o service para authApi de forma que fique:

private authApi: AuthApi

Fica mais descritivo e melhor de entender

2023-11-13 19:42 UTC, arthurpaesrizon commented on src/app/pages/auth/redirect/redirect.component.ts
>     * Função http request GET que pega o status e mensagem após o usuário clicar no link do e-mail de validação.
Aqui é bom descrever o exatamente a função ngOnInit faz, algo como: A função será disparada ao inicializar o componente, executando tais e tais funções

2023-11-13 19:49 UTC, arthurpaesrizon requested changes

2023-11-13 19:49 UTC, arthurpaesrizon commented on src/app/pages/dash/survey/survay.component.ts
> +export class SurvayComponent {
A nomenclatura correta é Survey, trocar em todos os campos

2023-11-13 19:49 UTC, arthurpaesrizon commented on src/app/pages/auth/auth.module.ts
> +import { redirectApi } from 'src/app/core/api/app/redirect.api';
Arquivo excluido. Remover

2023-11-13 19:49 UTC, arthurpaesrizon commented on src/app/pages/auth/auth.module.ts
> +  providers: [authApi, UserRegisterApi, redirectApi],
Arquivo excluido. Remover

2023-11-13 19:49 UTC, arthurpaesrizon commented on src/app/core/api/app/rating.api.ts
> +  constructor(private httpRating: HttpRequestService) {}
Usar sempre o mesmo nome para o service entre todos os componentes e utilizar o mesmo nome, mas com a letra inicial em minúsculo:

private httpRequestService: HttpRequestService

2023-11-13 19:49 UTC, arthurpaesrizon commented on src/app/core/api/app/auth.api.ts
> +    private httpService: HttpRequestService,
Usar sempre o mesmo nome para o service entre todos os componentes e utilizar o mesmo nome, mas com a letra inicial em minúsculo:

private httpRequestService: HttpRequestService

2023-11-13 19:49 UTC, arthurpaesrizon commented on src/app/components/rating/rating.component.ts
> +    private httpRating: RatingApi,
private ratingApi: RatingApi

2023-11-13 19:49 UTC, arthurpaesrizon commented on package.json
> +    "start": "ng serve --host 0.0.0.0 --poll 500",
Não precisas commitar isso

2023-11-14 13:51 UTC, rhorauti commented on src/app/core/api/app/auth.api.ts
> +    private httpRedirect: HttpRequestService,
Verdade. Desculpe. Alterado.

2023-11-14 13:51 UTC, rhorauti commented on src/app/core/api/app/auth.api.ts
>  export class authApi {
Alterado.

2023-11-14 13:52 UTC, rhorauti commented on src/app/core/api/app/auth.api.ts
> +    private httpService: HttpRequestService,
Entendi. Obrigado. Alterado.

2023-11-14 14:02 UTC, rhorauti commented on src/app/pages/auth/auth.module.ts
> +import { redirectApi } from 'src/app/core/api/app/redirect.api';
Ok. Excluido

2023-11-14 14:03 UTC, rhorauti commented on src/app/pages/auth/auth.module.ts
> +  providers: [authApi, UserRegisterApi, redirectApi],
Ok. Excluido

2023-11-14 14:04 UTC, rhorauti commented on src/app/core/api/app/rating.api.ts
> +  constructor(private httpRating: HttpRequestService) {}
Ok. Alterado.

2023-11-14 14:06 UTC, rhorauti commented on src/app/components/rating/rating.component.ts
> +    private httpRating: RatingApi,
OK. Alterado

2023-11-14 15:25 UTC, arthurpaesrizon approved these changes

2023-11-14 15:25 UTC, merged