Feature/feedback modal - login
arthurpaesrizon/marvelpedia-orionis-front pull request #32
Opened 2023-11-15 14:18 UTC by brennerpaiva

2023-11-16 17:49 UTC, arthurpaesrizon requested changes

2023-11-16 17:49 UTC, arthurpaesrizon commented on src/app/components/modal/modal.component.html
> +    (click)="closeOnOverlayClick ? closeModal() : null"
Aqui não consegues deixar da seguinte maneira?

```
closeOnOverlayClick && closeModal()
```

2023-11-16 17:49 UTC, arthurpaesrizon commented on src/app/pages/auth/login/login.component.ts
> +      .then(() => this.handleLoginSuccess())
Geralmente usa-se mais async/await encapsulando a requisição em um bloco try/catch. Acho que esqueci de mencionar. Se conseguires mudar beleza, se não, não tem problema.

2023-11-16 17:49 UTC, arthurpaesrizon commented on src/app/pages/auth/login/login.component.ts
> +    private authLogin: authApi,
Acredito que a classe authApi tenha sido renomeada para AuthApi, portanto, deixa da seguinte maneira:

```
    private authApi: AuthApi,
```

2023-11-16 17:49 UTC, arthurpaesrizon commented
Resolver conflitos

2023-11-18 18:29 UTC, brennerpaiva commented on src/app/pages/auth/login/login.component.ts
> +    private authLogin: authApi,
As correções foram feitas.

2023-11-20 21:40 UTC, arthurpaesrizon approved these changes

2023-11-20 21:40 UTC, merged