Feature/route protection
arthurpaesrizon/marvelpedia-orionis-front pull request #35
Opened 2023-11-17 04:55 UTC by brennerpaiva

2023-11-17 12:00 UTC, arthurpaesrizon requested changes

2023-11-17 12:00 UTC, arthurpaesrizon commented on src/environments/environment.ts
> +export const environment = {
Esse arquivo engloba qual ambiente?

2023-11-17 12:00 UTC, arthurpaesrizon commented on src/app/guards/auth.guard.ts
> +  async canActivate(
Faltou tsDoc da função

2023-11-17 12:00 UTC, arthurpaesrizon commented on src/app/core/api/http-request.service.ts
> +  private handleHttpError(error: HttpErrorResponse) {
Adicionar tsDoc e tipar retorno

2023-11-17 12:00 UTC, arthurpaesrizon commented on src/app/core/api/http-request.service.ts
> +    if (error.status === 403) {
O Status aqui é 401.

https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/403
O código de resposta de status de erro do cliente HTTP 403 Forbidden indica que o servidor entendeu o pedido, mas se recusa a autorizá-lo.

Esse status é semelhante ao [401](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/401) , mas neste caso, a re-autenticação não fará diferença. O acesso é permanentemente proibido e vinculado à lógica da aplicação (como uma senha incorreta).

2023-11-17 12:00 UTC, arthurpaesrizon commented on src/app/core/api/app/characters.api.ts
>    constructor(private httpGetCharacter: HttpRequestService) {}
É bom padronizar e deixar como:

```
private httpRequestService: HttpRequestService
```
em todos os arquivos

2023-11-17 12:00 UTC, arthurpaesrizon commented on src/app/core/api/app/new.user.api.ts
>    constructor(private httpService: HttpRequestService) {}
É bom padronizar e deixar como:

```
private httpRequestService: HttpRequestService
```
em todos os arquivos

2023-11-18 13:49 UTC, arthurpaesrizon commented on src/app/core/api/http-request.service.ts
> +  private handleHttpError(error: HttpErrorResponse): Observable<never> {
Coloca pelo menos um //TODO aqui pra quando o back corrigir o statusCode

2023-11-18 15:48 UTC, brennerpaiva commented on src/app/core/api/http-request.service.ts
> +  private handleHttpError(error: HttpErrorResponse): Observable<never> {
Feito!

2023-11-18 17:48 UTC, arthurpaesrizon approved these changes

2023-11-18 17:48 UTC, merged