Feature/search bar
arthurpaesrizon/marvelpedia-orionis-front pull request #41
Opened 2023-11-20 21:57 UTC by brennerpaiva

Troquei "character" por "content". Agora, os cards não vão ter apenas personagens, vamos ter outros conteúdos como: filmes, séries, quadirnhos e eventos. Optei por content por ser um nome mais genérico.

2023-11-22 09:05 UTC, arthurpaesrizon requested changes

2023-11-22 09:05 UTC, arthurpaesrizon commented on src/app/core/api/app/content.api.ts
> +export class ContentApi {
O Nome content não ficou muito descritivo, Content do quê?

2023-11-22 09:05 UTC, arthurpaesrizon commented on src/app/core/api/app/content.api.ts
> +  async getContent(
O Nome content não ficou muito descritivo, Content do quê?

2023-11-22 09:05 UTC, arthurpaesrizon commented on src/app/core/api/interfaces/IContent.ts
> +export interface IResponseContent {
O Nome content não ficou muito descritivo, Content do quê?

2023-11-22 09:05 UTC, arthurpaesrizon commented on src/app/pages/dash/home/home.component.ts
> +  searchContent() {
Tipar retorno

2023-11-22 09:05 UTC, arthurpaesrizon commented on src/app/pages/dash/home/home.component.ts
>        .then((response) => {
Em vez de usar then/catch, tenta usar async/Await e encapsular a requisição é um bloco try/catch. Fica mais organizado

2023-11-22 09:05 UTC, arthurpaesrizon commented on src/app/pages/dash/home/home.component.ts
> +    } else {
Esse else não é necessário, se cair no if e retornar, a função termina

2023-11-22 20:31 UTC, brennerpaiva commented on src/app/pages/dash/home/home.component.ts
> +    } else {
As alterações foram feitas!

2023-11-23 09:23 UTC, arthurpaesrizon commented
Resolver conflitos para aprovação

2023-11-23 09:35 UTC, arthurpaesrizon requested changes

2023-11-23 09:35 UTC, arthurpaesrizon commented on src/app/core/api/app/marvel-content.api.ts
> +  async getContentByCategorie(
Category*

2023-11-23 09:35 UTC, arthurpaesrizon commented on src/app/pages/dash/home/home.component.ts
> +  private translateCategory(categoryInPortuguese: string): EnumContentCategory {
Acredito que aqui tu possas usar um objeto em vez de um switch case:

const object = {personagens: 'characters', eventos: 'events'} etc...

return object[categoryInPortuguese.toLowerCase()]

2023-11-23 09:35 UTC, arthurpaesrizon commented on src/app/pages/dash/home/home.component.ts
>     * seeMoreCharacters() {
Trocar título no tsDoc

2023-11-23 09:35 UTC, arthurpaesrizon commented on src/app/pages/dash/home/home.component.ts
> +   * serviceGetCharacters
Trocar título da função no tsDoc

2023-11-23 09:35 UTC, arthurpaesrizon commented on src/app/pages/dash/home/home.component.ts
> +   * Manipula a mudança no input de texto da pesquisa.
Faltou acrescentar nome da função no tsDoc

2023-11-23 09:35 UTC, arthurpaesrizon commented on src/app/pages/dash/home/home.component.ts
> +export enum EnumContentCategory {
Declara esse enum dentro da interface de IContent

2023-11-23 09:35 UTC, arthurpaesrizon commented on src/app/core/api/interfaces/IContent.ts
> +
(é bom trocar o nome do arquivo para IMarvelContent, fica mais específico)

2023-11-23 12:36 UTC, brennerpaiva commented
As correções foram feitas.

2023-11-23 13:32 UTC, arthurpaesrizon approved these changes

2023-11-23 13:32 UTC, arthurpaesrizon commented on src/app/core/api/app/marvel-content.api.ts
> +   * getContentByCategorie
Faltou trocar o nome da função no tsDoc

2023-11-23 13:32 UTC, arthurpaesrizon commented
Só ajustar esse último comentário

2023-11-23 18:26 UTC, merged