Feature/comp modal
arthurpaesrizon/marvelpedia-orionis-front pull request #5
Opened 2023-10-21 19:31 UTC by rhorauti

2023-10-23 13:55 UTC, arthurpaesrizon requested changes

2023-10-23 13:55 UTC, arthurpaesrizon commented on Dockerfile
> +EXPOSE 4200 49153
Não é bom commitar isso por enquanto, pode ter efeitos adversos em ambiente que não sejam windows

2023-10-23 13:55 UTC, arthurpaesrizon commented on package.json
> +    "start": "ng serve --host 0.0.0.0 --poll 500",
Não é bom commitar isso por enquanto, pode ter efeitos adversos em ambiente que não sejam windows

2023-10-23 13:55 UTC, arthurpaesrizon commented on src/app/app.component.ts
>  export class AppComponent {
Mesma coisa. Essa lógica não precisar estar aqui, e sim nas páginas que utilizarão o modal

2023-10-23 13:55 UTC, arthurpaesrizon commented on src/app/components/modal/modal.component.html
> +        <button (click)="closeModal()" id="btn-finalizar">FINALIZAR</button>
A Label FINALIZAR será fixa?

2023-10-23 13:55 UTC, arthurpaesrizon commented on src/app/components/modal/modal.component.ts
> +  closeModal() {
Não cobramos durante os exercícios, mas vamos usar tsDoc no projeto para a documentação de funções https://tsdoc.org/

2023-10-23 13:55 UTC, arthurpaesrizon commented on src/app/components/modal/modal.component.ts
> +  closeModal() {
tipar retorno

2023-10-23 13:55 UTC, arthurpaesrizon commented on src/app/components/modal/modal.component.ts
> +  @Input() mensagem:string = '';
Seguir o padrão já adotado e utilizar variáveis em inglês

2023-10-24 01:44 UTC, rhorauti commented on src/app/components/modal/modal.component.html
> +        <button (click)="closeModal()" id="btn-finalizar">FINALIZAR</button>
Pelo que reparei na tela de login a label é igual em todas as situações.

2023-10-24 01:45 UTC, rhorauti commented on src/app/app.component.ts
>  export class AppComponent {
ok

2023-10-24 01:45 UTC, rhorauti commented on package.json
> +    "start": "ng serve --host 0.0.0.0 --poll 500",
ok

2023-10-24 01:45 UTC, rhorauti commented on Dockerfile
> +EXPOSE 4200 49153
ok

2023-10-24 01:45 UTC, rhorauti commented on src/app/components/modal/modal.component.ts
> +  closeModal() {
ok. inserido

2023-10-24 01:45 UTC, rhorauti commented on src/app/components/modal/modal.component.ts
> +  closeModal() {
ok. feito

2023-10-24 01:45 UTC, rhorauti commented on src/app/components/modal/modal.component.ts
> +  @Input() mensagem:string = '';
ok. corrigido

2023-10-24 02:30 UTC, rhorauti commented on src/app/components/modal/modal.component.ts
> +  @Input() mensagem:string = '';
ok

2023-10-24 21:42 UTC, arthurpaesrizon approved these changes

2023-10-24 21:49 UTC, merged