correção dos endpoints da tela de pesquisa de satisfação
arthurpaesrizon/marvelpedia-orionis-front pull request #61
Opened 2023-11-29 12:53 UTC by rhorauti

2023-11-29 22:47 UTC, arthurpaesrizon requested changes

2023-11-29 22:47 UTC, arthurpaesrizon commented on src/app/components/rating/rating.component.ts
> +   * Objeto que manipula o caso de sucesso no modal.
Adicionar parametro ao tsDoc

2023-11-29 22:47 UTC, arthurpaesrizon commented on src/app/components/rating/rating.component.ts
> +  handleRatingError(errorMessage: string): void {
Adicionar parametro ao tsDoc

2023-11-29 22:47 UTC, arthurpaesrizon commented on src/app/pages/auth/login/login.component.ts
> +        this.router.navigate(['/survey']);
Acredito que possas usar um return dentro do if ao invés de if else

2023-11-29 22:47 UTC, arthurpaesrizon commented on src/app/components/rating/rating.component.ts
> +      this.modalConfig.showModal = statusModal;
Acredito que possas usar um return dentro do if ao invés de if else

2023-11-29 22:47 UTC, arthurpaesrizon commented on src/app/components/rating/rating.component.ts
> +        this.handleRatingError(error.data.msg);
Acredito que possas usar um return dentro do if ao invés de if else

2023-11-29 22:47 UTC, arthurpaesrizon commented on src/app/components/rating/rating.component.ts
> +      if (error.data.msg) {
Podes me explicar o que esse if tá fazendo?

2023-11-30 00:54 UTC, arthurpaesrizon commented
Não achei o card dessa task no board. Consegues linkar aqui?

2023-12-02 16:53 UTC, rhorauti commented on src/app/components/rating/rating.component.ts
> +   * Objeto que manipula o caso de sucesso no modal.
Corrigido. Eu retirei o parâmetro pois não era necessário.

2023-12-02 16:53 UTC, rhorauti commented on src/app/components/rating/rating.component.ts
> +  handleRatingError(errorMessage: string): void {
Adicionado o parâmetro no TSDoc

2023-12-02 16:54 UTC, rhorauti commented on src/app/pages/auth/login/login.component.ts
> +        this.router.navigate(['/survey']);
Eu tentei colocar um return mas o ts reclama que a resposta por ser uma Promise<void> não é permitido.

2023-12-02 16:54 UTC, rhorauti commented on src/app/components/rating/rating.component.ts
> +      this.modalConfig.showModal = statusModal;
Eu tentei colocar um return mas o ts reclama que a resposta por ser uma Promise<void> não é permitido.

2023-12-02 16:55 UTC, rhorauti commented on src/app/components/rating/rating.component.ts
> +        this.handleRatingError(error.data.msg);
Eu tentei colocar um return mas o ts reclama que a resposta por ser uma Promise<void> não é permitido.

2023-12-02 16:59 UTC, rhorauti commented on src/app/components/rating/rating.component.ts
> +      if (error.data.msg) {
Existem 3 tipos de erros que vem do back (400, 422, 500). O erro 400 é relacionado a palavras ofensivas que tem o atributo "msg". Os erros 422 e 500 são relacionados a servidor e não possuem uma mensagem para ser exibida. Então o if que fiz da "msg" é para mostrar o erro para o usuário de palavras ofensivas e o else mostra um erro padrão de servidor.

2023-12-02 18:09 UTC, arthurpaesrizon commented on src/app/pages/auth/login/login.component.ts
> +        this.router.navigate(['/survey']);
Nesse caso daria para usar o promise.resolve(), mas deixa assim mesmo.

2023-12-02 18:10 UTC, arthurpaesrizon approved these changes

2023-12-04 17:24 UTC, brennerpaiva commented
![img123123123124](https://github.com/arthurpaesrizon/marvelpedia-orionis-front/assets/114958953/dd39748b-0a4b-4327-b001-49dfae26e177)
Ao clicar no "X" o usuário é direcionado de volta ao login, ele não deveria ser direcionado para a Home?

2023-12-04 21:56 UTC, brennerpaiva approved these changes

2023-12-05 02:25 UTC, rodrigodip approved these changes

2023-12-05 12:45 UTC, merged