Fix/password checker clear
arthurpaesrizon/marvelpedia-orionis-front pull request #63
Opened 2023-11-30 19:50 UTC by rodrigodip

2023-12-01 01:26 UTC, arthurpaesrizon requested changes
Creio que dê pra refatorar bastante coisa desses componente e deixar mais organizado/legível. Algumas coisas estão confusas. Como o tempo é curto não vou obrigar, mas fica a teu critério. Alterando o que comentei, eu já aprovo.

2023-12-01 01:26 UTC, arthurpaesrizon commented on src/app/pages/auth/sign-up/sign-up.component.ts
> +  handleFormRefresh() {
Faltou tsDoc e tipagem de retorno

2023-12-01 01:26 UTC, arthurpaesrizon commented on src/app/components/password-checker/password-checker.component.ts
> +  handleResetComponent() {
Tipagem de retorno

2023-12-05 12:44 UTC, arthurpaesrizon approved these changes
@brennerpaiva @rhorauti Testar antes de aprovar

2023-12-05 14:29 UTC, brennerpaiva approved these changes

2023-12-05 15:24 UTC, rhorauti approved these changes

2023-12-05 15:24 UTC, merged