Feature/compSelect
arthurpaesrizon/marvelpedia-orionis-front pull request #7
Opened 2023-10-24 16:32 UTC by rhorauti

2023-10-24 21:53 UTC, arthurpaesrizon requested changes

2023-10-24 21:53 UTC, arthurpaesrizon commented on src/app/components/select-genero/select-genero.component.ts
> +export class SelectGeneroComponent {
O Componente sempre deve ser abstrato, genérico e dinâmico. 
Quem irá passar a lista de opções para o componente de select será o componente pai. 
O select não deve armazenar essas informações

2023-10-24 21:53 UTC, arthurpaesrizon commented on src/app/components/select-genero/select-genero.component.ts
> +export class SelectGeneroComponent {
Renomear para SelectComponent

2023-10-24 21:53 UTC, arthurpaesrizon commented on src/app/components/select-genero/select-genero.component.html
> +    <option value="" disabled selected hidden>Selecione um genero</option>
Isso deve ser dinâmico

2023-10-25 11:41 UTC, rhorauti commented on src/app/components/select-genero/select-genero.component.ts
> +export class SelectGeneroComponent {
Ok. Feito

2023-10-25 11:41 UTC, rhorauti commented on src/app/components/select-genero/select-genero.component.ts
> +export class SelectGeneroComponent {
Ok. Feito.

2023-10-25 12:01 UTC, rhorauti commented on src/app/components/select-genero/select-genero.component.html
> +    <option value="" disabled selected hidden>Selecione um genero</option>
ok. Retirado

2023-10-25 19:02 UTC, arthurpaesrizon approved these changes

2023-10-25 19:03 UTC, merged