Feature/header Details
arthurpaesrizon/marvelpedia-orionis-front pull request #70
Opened 2023-12-05 14:04 UTC by brennerpaiva

2023-12-05 16:48 UTC, rhorauti approved these changes

2023-12-05 18:56 UTC, arthurpaesrizon requested changes

2023-12-05 18:56 UTC, arthurpaesrizon commented on src/app/pages/dash/character-details/character-details.component.html
> +  ContentDescription="Homem de Ferro é um personagem dos quadrinhos publicados pela Marvel Comics. Sua verdadeira identidade é o empresário e bilionário Tony Stark, que usa armaduras de alta tecnolog
Isso não deveria ser dinâmico?

2023-12-05 18:56 UTC, arthurpaesrizon commented on src/app/pages/dash/character-details/character-details.component.html
> +  ContentDescription="Homem de Ferro é um personagem dos quadrinhos publicados pela Marvel Comics. Sua verdadeira identidade é o empresário e bilionário Tony Stark, que usa armaduras de alta tecnolog
Se a API não estiver pronta, adicionar um //TODO

2023-12-05 19:43 UTC, brennerpaiva commented on src/app/pages/dash/character-details/character-details.component.html
> +  ContentDescription="Homem de Ferro é um personagem dos quadrinhos publicados pela Marvel Comics. Sua verdadeira identidade é o empresário e bilionário Tony Stark, que usa armaduras de alta tecnolog
Sim, apenas coloquei um exemplo de uso para o pessoal testar. Vou adicionar um //TODO

2023-12-05 23:21 UTC, arthurpaesrizon approved these changes

2023-12-06 10:28 UTC, rodrigodip approved these changes

2023-12-06 10:28 UTC, merged