Tela de login - Correção da mensagem de erro de e-mail não validado
arthurpaesrizon/marvelpedia-orionis-front pull request #75
Opened 2023-12-06 14:45 UTC by rhorauti

2023-12-06 17:52 UTC, arthurpaesrizon requested changes

2023-12-06 17:52 UTC, arthurpaesrizon commented on src/app/pages/auth/login/login.component.ts
> +      console.log(e);
Remover console log

2023-12-06 17:52 UTC, arthurpaesrizon commented on src/app/pages/auth/login/login.component.ts
> +        return;
pode remover o return

2023-12-06 17:59 UTC, rhorauti commented on src/app/pages/auth/login/login.component.ts
> +      console.log(e);
Ok. Removido

2023-12-06 18:00 UTC, rhorauti commented on src/app/pages/auth/login/login.component.ts
> +        return;
Ok. Removido.

2023-12-06 18:02 UTC, arthurpaesrizon approved these changes

2023-12-07 03:34 UTC, arthurpaesrizon commented
@brennerpaiva @rodrigodip Testar e aprovar

2023-12-07 12:55 UTC, brennerpaiva approved these changes

2023-12-07 15:22 UTC, merged