Fix: Ajusta lógica da verificação de data no formulário de cadastro.
arthurpaesrizon/marvelpedia-orionis-front pull request #76
Opened 2023-12-07 02:13 UTC by rodrigodip

2023-12-07 03:32 UTC, arthurpaesrizon requested changes

2023-12-07 03:32 UTC, arthurpaesrizon commented on src/app/pages/auth/sign-up/sign-up.component.ts
> +  }
Rod, esse código tá muito repetitivo. Componente inteiro tá assim. Tenta dar uma refatorada.
@brennerpaiva @rhorauti  Se puderem dar uma força pra pensar na refatoração

2023-12-08 13:46 UTC, brennerpaiva approved these changes

2023-12-08 21:27 UTC, arthurpaesrizon approved these changes

2023-12-08 21:27 UTC, merged